### ISSUE TITLE
Can't type at all in MacOS Safari

### ISSUE THREAD

**Issue by csuhta** [scryfall/art-game#1]
On Safari I cannot type any characters in the card name box and I can't focus the field

**Comment by FlorianMarsch** [comment]
Same Issue on Chrome on MacOs. Seems to be the @loadend event that you used to identify if the picture is loaded. Changed it to @load and all is fine :)

Line 30 index.html
<img class="art" v-bind:src="artUrl" @load="imageFinishedLoading">

**Comment by spacemonaut** [comment]
@FlorianMarsch I'm relieved that is the cause. That was the fix for IE 11 as well, which experienced the same problem.

**Comment by spacemonaut** [comment]
Confirmed resolved with testing.
