### ISSUE TITLE
Bad crop for Budoko Gardener

### ISSUE THREAD

**Issue by Meerkov** [scryfall/art-game#20]
https://img.scryfall.com/cards/art_crop/en/c18/134a.jpg?1535503797

The art crop includes the type line. My guess is all the flip cards have similar cropping issues. Not sure where to file it, so I figure art-game is an ok place.

**Comment by spacemonaut** [comment]
Thanks for the report! After looking into this it seems like it's a problem with flip cards printed with the new 2015 frame, so it also shows up for [Nezumi Graverobber](https://scryfall.com/card/cm2/71/nezumi-graverobber-nighteyes-the-desecrator). I've forwarded it on to Scryfall's main feedback where it will get resolved.
