### ISSUE TITLE
Add Scryfall logo and the words "Art Game" to the top of the page

### ISSUE THREAD

**Issue by csuhta** [scryfall/art-game#7]
This doesn't need to be a large element, but some way to identify the site and that it's run by Scryfall is needed.

Scryfall logo attached as an SVG:

[header-logo.svg.zip](https://github.com/scryfall/art-game/files/2631049/header-logo.svg.zip)

**Comment by csuhta** [comment]
Also clicking this element should take you to the root of the site and/or start the game over

**Comment by spacemonaut** [comment]
Resolved as of 7f76141feb2c6737aa486d82331724fc87c27a1f
